#
# Copyright (C) 2019 GIP-RECIA https://www.recia.fr/
# @Author (C) 2019 Pierre Legay <pierre.legay@recia.fr>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#                 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  address: 192.168.45.196
  port: 8443
  ssl:
    enabled: false
    key-alias: tomcat-localhost
    # key-password: 
    key-store: classpath:menucantine.jks
    key-store-provider: SUN
    key-store-type: JKS
    # key-store-password: 
  servlet:
    contextPath: /menuCantine
    
soffit:
  # jwt.signatureKey: 
  anonymous:
    getacces: /api/lastmenu
    postacces: /api/demomenu

adoria:
  url: https://api.adoria.com/Api/EProduction/CycleMenu/GetCycleMenusForEnt
  # client-key: 
  # guid: 
  gemrcn-csv: classpath:GemRcn.csv
  labels-csv: classpath:labels.csv
  test:
    no-web-service: false
    format-fileName: classpath:static/test/menuTest%d.json
 
logging:
  file: /home/esco/logs/menucantine
  level: 
    web: info
    web.servlet.DispatcherServlet: info
    fr:
      recia:
        menucantine: info

spring:
  cache:
    type: ehcache

