server:
  address: 192.168.45.196
  port: 8443
  ssl:
    enabled: true
    key-alias: tomcat-localhost
    # key-password: 
    key-store: /home/legay/SpringBoot/demoSpringBootCas/keystore.jks
    key-store-provider: SUN
    key-store-type: JKS
    # key-store-password: 
  servlet:
    contextPath: /menuCantine
    
soffit:
  # jwt.signatureKey: 
  anonymous:
    getacces: /api/lastmenu
    postacces: /api/demomenu

adoria:
  url: https://api.adoria.com/Api/EProduction/CycleMenu/GetCycleMenusForEnt
  # client-key: 
  # guid: 
  test:
    no-web-service: false
    format-fileName: classpath:static/test/menuTest%d.json
 
logging:
  level: 
    web: debug
    web.servlet.DispatcherServlet: trace
    fr:
      recia:
        menucantine: DEBUG
